name: DL4OPF
channels:
  - pytorch
  - defaults
dependencies:
  - appnope=0.1.0=py38_1001
  - argon2-cffi=20.1.0=py38haf1e3a3_1
  - astroid=2.4.2=py38_0
  - attrs=20.1.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.2=py38hed5b41f_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.16=h18a8e69_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.9=hb1e8313_2
  - freetype=2.10.2=ha233b18_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.65.0=hc5f4afa_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=1.7.0=py38_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - isort=5.4.2=py38_0
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py38_1
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - kiwisolver=1.2.0=py38h04f5b5a_0
  - lazy-object-proxy=1.4.3=py38h1de35cc_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.1.0=hcb84e12_1
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=hb1e8313_1
  - markupsafe=1.1.1=py38h1de35cc_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38h181983e_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.1.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - nbconvert=5.6.1=py38_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=h0a44026_1
  - ninja=1.10.1=py38h879752b_0
  - notebook=6.1.1=py38_0
  - numpy-base=1.19.1=py38hcfb5961_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h1de35cc_0
  - packaging=20.4=py_0
  - pandas=1.1.1=py38hb1e8313_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=py38_1
  - pickleshare=0.7.5=py38_1001
  - pillow=7.2.0=py38ha54b6ba_0
  - pip=20.2.2=py38_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - ptyprocess=0.6.0=py38_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=py_2
  - pygments=2.6.1=py_0
  - pylint=2.6.0=py38_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.16.0=py38h1de35cc_0
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - pytorch=1.6.0=py3.8_0
  - pytz=2020.1=py_0
  - pyzmq=19.0.1=py38hb1e8313_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.6=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - scikit-learn=0.23.2=py38h959d312_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py38_0
  - setuptools=49.6.0=py38_0
  - simplejson=3.17.2=py38haf1e3a3_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=hffcf06c_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.1=py_0
  - torchvision=0.7.0=py38_cpu
  - tornado=6.0.4=py38h1de35cc_1
  - traitlets=4.3.3=py38_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.11.2=py38h1de35cc_0
  - xz=5.2.5=h1de35cc_0
  - yapf=0.30.0=py_0
  - zeromq=4.3.2=hb1e8313_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - cachetools==4.1.1
    - chardet==3.0.4
    - dgl==0.5.1
    - gast==0.3.3
    - google-auth==1.21.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - keras-preprocessing==1.1.2
    - lxml==4.5.2
    - markdown==3.2.2
    - networkx==2.5
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.4.1
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - urllib3==1.25.10
    - werkzeug==1.0.1
prefix: /Users/jeehyunpark/opt/anaconda3/envs/DL4OPF
